import type { Metadata } from "next";
import { Inter, Poppins, Montserrat } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  variable: "--poppins",
  weight: ["100", "200", "300", "400", "500", "600"],
  subsets: ["latin"],
});

const monserrat = Montserrat({
  variable: "--monserrat",
  weight: ["100", "200", "300", "400", "500", "600", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${poppins.variable} ${monserrat.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
